"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
exports.__esModule = true;
exports.InputTokens = exports.SwitchTokens = exports.RadioTokens = exports.CheckboxTokens = exports.DropdownTokens = exports.ButtonTokens = exports.NavigationTokens = exports.GenericStateTokens = exports.GenericTokens = void 0;
var atomico_1 = require("atomico");
exports.GenericTokens = (0, atomico_1.css)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    @tokens \"./tokens.yaml\" (import: generic) (values: true);\n    :host {\n        font-size: var(--font-size);\n        line-height: var(--font-line);\n        --outline-color: var(--color-outline);\n        --outline: var(--outline-width) var(--outline-style)\n            var(--outline-color);\n    }\n    :host([disabled]) {\n        opacity: var(--opacity);\n        pointer-events: none;\n    }\n    :host([focused]:not([disabled])) {\n        --outline-color: var(--color-outline-on);\n    }\n"], ["\n    @tokens \"./tokens.yaml\" (import: generic) (values: true);\n    :host {\n        font-size: var(--font-size);\n        line-height: var(--font-line);\n        --outline-color: var(--color-outline);\n        --outline: var(--outline-width) var(--outline-style)\n            var(--outline-color);\n    }\n    :host([disabled]) {\n        opacity: var(--opacity);\n        pointer-events: none;\n    }\n    :host([focused]:not([disabled])) {\n        --outline-color: var(--color-outline-on);\n    }\n"])));
exports.GenericStateTokens = (0, atomico_1.css)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    @tokens \"./tokens.yaml\" (filter: state);\n"], ["\n    @tokens \"./tokens.yaml\" (filter: state);\n"])));
exports.NavigationTokens = (0, atomico_1.css)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    @tokens \"./tokens.yaml\" (import: navigation);\n"], ["\n    @tokens \"./tokens.yaml\" (import: navigation);\n"])));
exports.ButtonTokens = (0, atomico_1.css)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    @tokens \"./tokens.yaml\" (import: button);\n"], ["\n    @tokens \"./tokens.yaml\" (import: button);\n"])));
exports.DropdownTokens = (0, atomico_1.css)(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n    @tokens \"./tokens.yaml\" (import: dropdown);\n"], ["\n    @tokens \"./tokens.yaml\" (import: dropdown);\n"])));
exports.CheckboxTokens = (0, atomico_1.css)(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n    @tokens \"./tokens.yaml\" (import: checkbox);\n"], ["\n    @tokens \"./tokens.yaml\" (import: checkbox);\n"])));
exports.RadioTokens = (0, atomico_1.css)(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n    @tokens \"./tokens.yaml\" (import: radio);\n"], ["\n    @tokens \"./tokens.yaml\" (import: radio);\n"])));
exports.SwitchTokens = (0, atomico_1.css)(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n    @tokens \"./tokens.yaml\" (import: switch);\n"], ["\n    @tokens \"./tokens.yaml\" (import: switch);\n"])));
exports.InputTokens = (0, atomico_1.css)(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n    @tokens \"./tokens.yaml\" (import: input);\n"], ["\n    @tokens \"./tokens.yaml\" (import: input);\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9;
