export declare const GenericTokens: import("atomico").Sheet;
export declare const GenericStateTokens: import("atomico").Sheet;
export declare const NavigationTokens: import("atomico").Sheet;
export declare const ButtonTokens: import("atomico").Sheet;
export declare const DropdownTokens: import("atomico").Sheet;
export declare const CheckboxTokens: import("atomico").Sheet;
export declare const RadioTokens: import("atomico").Sheet;
export declare const SwitchTokens: import("atomico").Sheet;
export declare const InputTokens: import("atomico").Sheet;
